import type { jsPDF } from 'jspdf'
import type { ReportJson } from './analysisAgent'

const DISCLAIMER =
  'Hypothetical / AI-generated analysis, not investment advice. Not a guarantee of future results. Generated by CSE Sage from ceyloncharts-mcp data.'

function addWrapped(doc: jsPDF, text: string, x: number, y: number, maxWidth: number, lineHeight = 4.6): number {
  const lines = doc.splitTextToSize(text, maxWidth)
  doc.text(lines, x, y)
  return y + lines.length * lineHeight
}

function sectionHeading(doc: jsPDF, title: string, y: number, x: number): number {
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(11)
  doc.text(title, x, y)
  doc.setFont('helvetica', 'normal')
  doc.setFontSize(9)
  return y + 5
}

export async function generatePdfReport(opts: { symbol: string; report: ReportJson; chartPng?: string }): Promise<jsPDF> {
  const { jsPDF } = await import('jspdf')
  const doc = new jsPDF({ unit: 'mm', format: 'a4' })
  const marginX = 15
  const pageWidth = doc.internal.pageSize.getWidth()
  const contentWidth = pageWidth - marginX * 2

  // Page 1
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(18)
  doc.text(opts.symbol, marginX, 20)
  doc.setFont('helvetica', 'normal')
  doc.setFontSize(9)
  doc.setTextColor(120)
  doc.text(`CSE Sage AI analysis — generated ${new Date().toISOString().slice(0, 10)}`, marginX, 26)
  doc.setTextColor(0)

  let y = 34
  if (opts.chartPng) {
    const imgWidth = contentWidth
    const imgHeight = imgWidth * 0.5
    doc.addImage(`data:image/png;base64,${opts.chartPng}`, 'PNG', marginX, y, imgWidth, imgHeight)
    y += imgHeight + 8
  }

  y = sectionHeading(doc, 'Technical summary', y, marginX)
  y = addWrapped(doc, opts.report.technical_summary, marginX, y, contentWidth) + 4

  y = sectionHeading(doc, 'Overall verdict', y, marginX)
  y = addWrapped(doc, opts.report.verdict, marginX, y, contentWidth) + 4

  y = sectionHeading(doc, 'Income statement', y, marginX)
  y = addWrapped(doc, opts.report.income_summary, marginX, y, contentWidth) + 4

  y = sectionHeading(doc, 'Balance sheet', y, marginX)
  addWrapped(doc, opts.report.balance_summary, marginX, y, contentWidth)

  addFooter(doc, pageWidth)

  // Page 2
  doc.addPage()
  y = 20
  y = sectionHeading(doc, 'Cash flow', y, marginX)
  y = addWrapped(doc, opts.report.cashflow_summary, marginX, y, contentWidth) + 6

  y = sectionHeading(doc, 'Shareholding changes', y, marginX)
  y = addWrapped(doc, opts.report.shareholding_summary, marginX, y, contentWidth) + 6

  y = sectionHeading(doc, 'Recent announcements', y, marginX)
  addWrapped(doc, opts.report.announcements_summary, marginX, y, contentWidth)

  addFooter(doc, pageWidth)

  return doc
}

function addFooter(doc: jsPDF, pageWidth: number) {
  const pageHeight = doc.internal.pageSize.getHeight()
  doc.setFontSize(7)
  doc.setTextColor(150)
  const lines = doc.splitTextToSize(DISCLAIMER, pageWidth - 30)
  doc.text(lines, 15, pageHeight - 12)
  doc.setTextColor(0)
}
